modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="derenium"
version="Early Alpha 1.1"
displayName="Derenium"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Mjelony"

[[dependencies.derenium]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




